name: Update Loan Rates

on:
  schedule:
    - cron: "0 4 * * *"   # Runs every day at 4 AM UTC (9 AM PKT)
  workflow_dispatch:       # Allows manual run from GitHub Actions tab

jobs:
  update-rates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push updated rates.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add rates.json
          git commit -m "Auto-update rates.json [skip ci]" || echo "No changes to commit"
          git push
